on:
  push:
    branches:
    - main

jobs:
  build:
    name: build site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "107.180.54.236 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMVDw43wCkWtKYQuVbFoT14uiFQ6uf8aj0w+lB2fulJF" > ~/.ssh/known_hosts
          ssh-keygen -Hf ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      - name: sftp files to webserver 
        run: |
          echo "put -r dist/* public_html/" > sftp-commands.txt
          sftp -b sftp-commands.txt grslfootball@107.180.54.236
  
